CREATE TABLE audit_logs
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active   BOOLEAN,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    is_deleted  BOOLEAN,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    user_id     BIGINT,
    action      VARCHAR(50)                             NOT NULL,
    table_name  VARCHAR(50)                             NOT NULL,
    record_id   INTEGER,
    old_value   JSONB,
    new_value   JSONB,
    ip_address  VARCHAR(45),
    user_agent  TEXT,
    description TEXT,
    CONSTRAINT pk_audit_logs PRIMARY KEY (id)
);

CREATE TABLE booking_combos
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active   BOOLEAN,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    is_deleted  BOOLEAN,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    booking_id  BIGINT                                  NOT NULL,
    combo_id    BIGINT                                  NOT NULL,
    quantity    INTEGER                                 NOT NULL,
    unit_price  DECIMAL(10, 2)                          NOT NULL,
    total_price DECIMAL(10, 2)                          NOT NULL,
    CONSTRAINT pk_booking_combos PRIMARY KEY (id)
);

CREATE TABLE booking_seats
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active   BOOLEAN,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    is_deleted  BOOLEAN,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    showtime_id BIGINT                                  NOT NULL,
    booking_id  BIGINT                                  NOT NULL,
    seat_id     BIGINT                                  NOT NULL,
    price       DECIMAL(10, 2)                          NOT NULL,
    CONSTRAINT pk_booking_seats PRIMARY KEY (id)
);

CREATE TABLE bookings
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active       BOOLEAN,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    is_deleted      BOOLEAN,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    user_id         BIGINT                                  NOT NULL,
    showtime_id     BIGINT                                  NOT NULL,
    booking_code    VARCHAR(20)                             NOT NULL,
    total_amount    DECIMAL(10, 2)                          NOT NULL,
    discount_amount DECIMAL(10, 2),
    final_amount    DECIMAL(10, 2)                          NOT NULL,
    status          VARCHAR(20),
    seat_snapshots  JSONB,
    booking_date    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    expires_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_bookings PRIMARY KEY (id)
);

CREATE TABLE cinemas
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active   BOOLEAN                                 NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    is_deleted  BOOLEAN,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    name        VARCHAR(255)                            NOT NULL,
    address     VARCHAR(500)                            NOT NULL,
    description TEXT,
    slug        VARCHAR(255)                            NOT NULL,
    region_id   BIGINT                                  NOT NULL,
    latitude    DOUBLE PRECISION,
    longitude   DOUBLE PRECISION,
    CONSTRAINT pk_cinemas PRIMARY KEY (id)
);

CREATE TABLE combos
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active   BOOLEAN,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    is_deleted  BOOLEAN,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    name        VARCHAR(255)                            NOT NULL,
    description TEXT,
    price       DECIMAL(10, 2)                          NOT NULL,
    image_url   VARCHAR(500),
    CONSTRAINT pk_combos PRIMARY KEY (id)
);

CREATE TABLE genres
(
    id         BIGINT       NOT NULL,
    is_active  BOOLEAN,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    is_deleted BOOLEAN,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    name       VARCHAR(100) NOT NULL,
    CONSTRAINT pk_genres PRIMARY KEY (id)
);

CREATE TABLE login_history
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active    BOOLEAN,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    is_deleted   BOOLEAN,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    user_id      BIGINT,
    email        VARCHAR(255),
    login_status VARCHAR(20)                             NOT NULL,
    ip_address   VARCHAR(45),
    user_agent   TEXT,
    device_type  VARCHAR(50),
    browser      VARCHAR(50),
    location     VARCHAR(255),
    fail_reason  VARCHAR(255),
    CONSTRAINT pk_login_history PRIMARY KEY (id)
);

CREATE TABLE movie_casts
(
    people_type VARCHAR(255),
    movie_id    BIGINT NOT NULL,
    people_id   BIGINT NOT NULL,
    CONSTRAINT pk_movie_casts PRIMARY KEY (movie_id, people_id)
);

CREATE TABLE movie_genres
(
    movie_id BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,
    CONSTRAINT pk_movie_genres PRIMARY KEY (movie_id, genre_id)
);

CREATE TABLE movie_versions
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active         BOOLEAN,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    is_deleted        BOOLEAN,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    movie_id          BIGINT                                  NOT NULL,
    name              VARCHAR(255),
    projection_type   VARCHAR(255),
    audio_language    VARCHAR(255),
    subtitle_language VARCHAR(255),
    CONSTRAINT pk_movie_versions PRIMARY KEY (id)
);

CREATE TABLE movies
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active      BOOLEAN,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    is_deleted     BOOLEAN,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    title          VARCHAR(255)                            NOT NULL,
    slug           VARCHAR(255)                            NOT NULL,
    original_title VARCHAR(255),
    description    TEXT,
    duration       INTEGER                                 NOT NULL,
    release_date   date                                    NOT NULL,
    age_rating     VARCHAR(10),
    poster_url     VARCHAR(500),
    backdrop_url   VARCHAR(500),
    trailer_url    VARCHAR(500),
    status         VARCHAR(255),
    CONSTRAINT pk_movies PRIMARY KEY (id)
);

CREATE TABLE notifications
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active  BOOLEAN,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    is_deleted BOOLEAN,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    title      VARCHAR(255),
    message    VARCHAR(255),
    type       VARCHAR(255),
    is_read    BOOLEAN,
    user_id    BIGINT,
    CONSTRAINT pk_notifications PRIMARY KEY (id)
);

CREATE TABLE payments
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active       BOOLEAN,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    is_deleted      BOOLEAN,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    booking_id      BIGINT                                  NOT NULL,
    amount          DECIMAL(10, 2)                          NOT NULL,
    payment_method  VARCHAR(50)                             NOT NULL,
    payment_status  VARCHAR(20),
    transaction_id  VARCHAR(255),
    payment_details TEXT,
    payment_date    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_payments PRIMARY KEY (id)
);

CREATE TABLE peoples
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active   BOOLEAN,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    is_deleted  BOOLEAN,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    name        VARCHAR(255)                            NOT NULL,
    slug        VARCHAR(255),
    bio         TEXT                                    NOT NULL,
    description TEXT                                    NOT NULL,
    avatar_url  TEXT                                    NOT NULL,
    CONSTRAINT pk_peoples PRIMARY KEY (id)
);

CREATE TABLE permissions
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active   BOOLEAN,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    is_deleted  BOOLEAN,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    name        VARCHAR(100)                            NOT NULL,
    description TEXT,
    module      VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_permissions PRIMARY KEY (id)
);

CREATE TABLE price_rules
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active        BOOLEAN,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    is_deleted       BOOLEAN,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    name             VARCHAR(255)                            NOT NULL,
    seat_type        VARCHAR(20),
    day_type         VARCHAR(20),
    time_from        time WITHOUT TIME ZONE,
    time_to          time WITHOUT TIME ZONE,
    price_adjustment DECIMAL(10, 2)                          NOT NULL,
    adjustment_type  VARCHAR(20),
    CONSTRAINT pk_price_rules PRIMARY KEY (id)
);

CREATE TABLE promotions
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active      BOOLEAN,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    is_deleted     BOOLEAN,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    code           VARCHAR(50)                             NOT NULL,
    name           VARCHAR(255)                            NOT NULL,
    description    TEXT,
    discount_type  VARCHAR(20)                             NOT NULL,
    discount_value DECIMAL(10, 2)                          NOT NULL,
    min_purchase   DECIMAL(10, 2),
    max_discount   DECIMAL(10, 2),
    usage_limit    INTEGER,
    used_count     INTEGER,
    start_date     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_promotions PRIMARY KEY (id)
);

CREATE TABLE refresh_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active  BOOLEAN,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    is_deleted BOOLEAN,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    token      TEXT                                    NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id)
);

CREATE TABLE regions
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active  BOOLEAN,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    is_deleted BOOLEAN,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    name       VARCHAR(100)                            NOT NULL,
    slug       VARCHAR(100)                            NOT NULL,
    category   VARCHAR(255)                            NOT NULL,
    alias      VARCHAR(255),
    CONSTRAINT pk_regions PRIMARY KEY (id)
);

CREATE TABLE reviews
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active        BOOLEAN,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    is_deleted       BOOLEAN,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    user_id          BIGINT                                  NOT NULL,
    movie_id         BIGINT                                  NOT NULL,
    rating           INTEGER                                 NOT NULL,
    comment          TEXT,
    parent_review_id BIGINT,
    CONSTRAINT pk_reviews PRIMARY KEY (id)
);

CREATE TABLE role_permissions
(
    role_id       BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    CONSTRAINT pk_role_permissions PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE roles
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active   BOOLEAN,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    is_deleted  BOOLEAN,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    name        VARCHAR(50)                             NOT NULL,
    description TEXT,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE rooms
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active       BOOLEAN,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    is_deleted      BOOLEAN,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    cinema_id       BIGINT                                  NOT NULL,
    name            VARCHAR(100)                            NOT NULL,
    description     TEXT,
    total_seats     INTEGER,
    screen_format   VARCHAR(255),
    projection_type VARCHAR(20),
    audio_type      VARCHAR(50),
    CONSTRAINT pk_rooms PRIMARY KEY (id)
);

CREATE TABLE seats
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active   BOOLEAN                                 NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    is_deleted  BOOLEAN,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    room_id     BIGINT                                  NOT NULL,
    row_label   VARCHAR(10)                             NOT NULL,
    seat_number INTEGER                                 NOT NULL,
    pos_x       INTEGER                                 NOT NULL,
    pos_y       INTEGER                                 NOT NULL,
    seat_type   VARCHAR(20),
    group_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_seats PRIMARY KEY (id)
);

CREATE TABLE showtimes
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active        BOOLEAN                                 NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    is_deleted       BOOLEAN,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    movie_version_id BIGINT                                  NOT NULL,
    room_id          BIGINT                                  NOT NULL,
    showtime_type    VARCHAR(20),
    start_at         TIMESTAMP WITHOUT TIME ZONE,
    base_price       DECIMAL(10, 2)                          NOT NULL,
    status           VARCHAR(20),
    CONSTRAINT pk_showtimes PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id)
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active     BOOLEAN,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    is_deleted    BOOLEAN,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    email         VARCHAR(255)                            NOT NULL,
    password      VARCHAR(255),
    full_name     VARCHAR(255)                            NOT NULL,
    phone         VARCHAR(20),
    address       VARCHAR(500),
    avatar_url    VARCHAR(500),
    date_of_birth date,
    provider_type VARCHAR(20),
    last_login    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE bookings
    ADD CONSTRAINT uc_bookings_booking_code UNIQUE (booking_code);

ALTER TABLE cinemas
    ADD CONSTRAINT uc_cinemas_slug UNIQUE (slug);

ALTER TABLE genres
    ADD CONSTRAINT uc_genres_name UNIQUE (name);

ALTER TABLE permissions
    ADD CONSTRAINT uc_permissions_name UNIQUE (name);

ALTER TABLE promotions
    ADD CONSTRAINT uc_promotions_code UNIQUE (code);

ALTER TABLE regions
    ADD CONSTRAINT uc_regions_name UNIQUE (name);

ALTER TABLE regions
    ADD CONSTRAINT uc_regions_slug UNIQUE (slug);

ALTER TABLE roles
    ADD CONSTRAINT uc_roles_name UNIQUE (name);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE seats
    ADD CONSTRAINT unique_seat UNIQUE ();

ALTER TABLE reviews
    ADD CONSTRAINT unique_user_movie UNIQUE (user_id, movie_id);

ALTER TABLE audit_logs
    ADD CONSTRAINT FK_AUDIT_LOGS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE bookings
    ADD CONSTRAINT FK_BOOKINGS_ON_SHOWTIME FOREIGN KEY (showtime_id) REFERENCES showtimes (id);

ALTER TABLE bookings
    ADD CONSTRAINT FK_BOOKINGS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE booking_combos
    ADD CONSTRAINT FK_BOOKING_COMBOS_ON_BOOKING FOREIGN KEY (booking_id) REFERENCES bookings (id);

ALTER TABLE booking_combos
    ADD CONSTRAINT FK_BOOKING_COMBOS_ON_COMBO FOREIGN KEY (combo_id) REFERENCES combos (id);

ALTER TABLE booking_seats
    ADD CONSTRAINT FK_BOOKING_SEATS_ON_BOOKING FOREIGN KEY (booking_id) REFERENCES bookings (id);

ALTER TABLE booking_seats
    ADD CONSTRAINT FK_BOOKING_SEATS_ON_SEAT FOREIGN KEY (seat_id) REFERENCES seats (id);

ALTER TABLE booking_seats
    ADD CONSTRAINT FK_BOOKING_SEATS_ON_SHOWTIME FOREIGN KEY (showtime_id) REFERENCES showtimes (id);

ALTER TABLE cinemas
    ADD CONSTRAINT FK_CINEMAS_ON_REGION FOREIGN KEY (region_id) REFERENCES regions (id);

ALTER TABLE login_history
    ADD CONSTRAINT FK_LOGIN_HISTORY_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE movie_casts
    ADD CONSTRAINT FK_MOVIE_CASTS_ON_MOVIE FOREIGN KEY (movie_id) REFERENCES movies (id);

ALTER TABLE movie_casts
    ADD CONSTRAINT FK_MOVIE_CASTS_ON_PEOPLE FOREIGN KEY (people_id) REFERENCES peoples (id);

ALTER TABLE movie_genres
    ADD CONSTRAINT FK_MOVIE_GENRES_ON_GENRE FOREIGN KEY (genre_id) REFERENCES genres (id);

ALTER TABLE movie_genres
    ADD CONSTRAINT FK_MOVIE_GENRES_ON_MOVIE FOREIGN KEY (movie_id) REFERENCES movies (id);

ALTER TABLE movie_versions
    ADD CONSTRAINT FK_MOVIE_VERSIONS_ON_MOVIE FOREIGN KEY (movie_id) REFERENCES movies (id);

ALTER TABLE notifications
    ADD CONSTRAINT FK_NOTIFICATIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE payments
    ADD CONSTRAINT FK_PAYMENTS_ON_BOOKING FOREIGN KEY (booking_id) REFERENCES bookings (id);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT FK_REFRESH_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE reviews
    ADD CONSTRAINT FK_REVIEWS_ON_MOVIE FOREIGN KEY (movie_id) REFERENCES movies (id);

ALTER TABLE reviews
    ADD CONSTRAINT FK_REVIEWS_ON_PARENT_REVIEW FOREIGN KEY (parent_review_id) REFERENCES reviews (id);

ALTER TABLE reviews
    ADD CONSTRAINT FK_REVIEWS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE role_permissions
    ADD CONSTRAINT FK_ROLE_PERMISSIONS_ON_PERMISSION FOREIGN KEY (permission_id) REFERENCES permissions (id);

ALTER TABLE role_permissions
    ADD CONSTRAINT FK_ROLE_PERMISSIONS_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE rooms
    ADD CONSTRAINT FK_ROOMS_ON_CINEMA FOREIGN KEY (cinema_id) REFERENCES cinemas (id);

ALTER TABLE seats
    ADD CONSTRAINT FK_SEATS_ON_ROOM FOREIGN KEY (room_id) REFERENCES rooms (id);

ALTER TABLE showtimes
    ADD CONSTRAINT FK_SHOWTIMES_ON_MOVIE_VERSION FOREIGN KEY (movie_version_id) REFERENCES movie_versions (id);

ALTER TABLE showtimes
    ADD CONSTRAINT FK_SHOWTIMES_ON_ROOM FOREIGN KEY (room_id) REFERENCES rooms (id);

ALTER TABLE user_roles
    ADD CONSTRAINT FK_USER_ROLES_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE user_roles
    ADD CONSTRAINT FK_USER_ROLES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);