import {
  BarChart3,
  BellRing,
  Calendar,
  Coffee,
  CreditCard,
  FileText,
  Gift,
  LayoutDashboard,
  Lock,
  MessageSquare,
  Settings,
  Shield,
  Store,
  Users,
  Video,
} from 'lucide-react';

export const adminNavigation = [
  { href: '/admin/dashboard', icon: <LayoutDashboard className="h-4 w-4" />, label: 'Dashboard' },
  { href: '/admin/movies', icon: <Video className="h-4 w-4" />, label: 'Quản lý phim' },
  { href: '/admin/cinemas', icon: <Store className="h-4 w-4" />, label: 'Quản lý rạp' },
  { href: '/admin/comments', icon: <MessageSquare className="h-4 w-4" />, label: 'Bình luận' },
  { href: '/admin/schedules', icon: <Calendar className="h-4 w-4" />, label: 'Lịch chiếu' },
  { href: '/admin/users', icon: <Users className="h-4 w-4" />, label: 'Người dùng' },
  { href: '/admin/bookings', icon: <FileText className="h-4 w-4" />, label: 'Đặt vé' },
  { href: '/admin/payment', icon: <CreditCard className="h-4 w-4" />, label: 'Thanh toán' },
  { href: '/admin/reports', icon: <BarChart3 className="h-4 w-4" />, label: 'Báo cáo' },
  { href: '/admin/promotions', icon: <Gift className="h-4 w-4" />, label: 'Khuyến mãi' },
  { href: '/admin/notifications', icon: <BellRing className="h-4 w-4" />, label: 'Thông báo' },
  { href: '/admin/staff', icon: <Shield className="h-4 w-4" />, label: 'Nhân viên' },
  { href: '/admin/roles-permissions', icon: <Lock className="h-4 w-4" />, label: 'Vai trò & Quyền' },
  { href: '/admin/food-beverage', icon: <Coffee className="h-4 w-4" />, label: 'Đồ ăn & Đồ uống' },
  { href: '/admin/settings', icon: <Settings className="h-4 w-4" />, label: 'Cài đặt' },
];
